style: {
  opacity: 1.0
}

team: Team Based Template {
  img1: "Frontend" {
    style: {
      stroke-dash: 10
      stroke-width: 1
    }
    frontend: "" {
      shape: image
      icon: https://raw.githubusercontent.com/matifali/logos/main/frontend-2.svg
    }
  }
  img2: "Backend" {
    style: {
      stroke-dash: 10
      stroke-width: 1
    }
    backend: "" {
      shape: image
      icon: https://raw.githubusercontent.com/matifali/logos/main/backend-2.svg
    }
  }
}

project: Project Based Template {
  img1: "Ticketing App" {
    style: {
      stroke-dash: 10
      stroke-width: 1
    }
    Java: {
      shape: image
      icon: https://raw.githubusercontent.com/matifali/logos/main/java.svg
    }
    Bazel: {
      shape: image
      icon: https://raw.githubusercontent.com/matifali/logos/main/bazel.svg
    }
    Spring Boot: {
      shape: image
      icon: https://raw.githubusercontent.com/matifali/logos/main/springboot-1.svg
    }
  }
  img2: "Billing Dashboard" {
    style: {
      stroke-dash: 10
      stroke-width: 1
    }
    React: {
      shape: image
      icon: https://raw.githubusercontent.com/matifali/logos/main/react.svg
    }
    TypeScript: {
      shape: image
      icon: https://raw.githubusercontent.com/matifali/logos/main/typescript.svg
    }
    MongoDB: {
      shape: image
      icon: https://raw.githubusercontent.com/matifali/logos/main/mongodb-green.svg
    }
  }
}

framework: Image Based Template {
  img1: PyTorch {
    style: {
      stroke-dash: 10
      stroke-width: 1
    }
    torch: "" {
      shape: image
      icon: https://raw.githubusercontent.com/matifali/logos/main/pytorch.svg
    }
  }
  img2: PyTorch Nightly {
    style: {
      stroke-dash: 10
      stroke-width: 1
    }
    torch-n: "" {
      shape: image
      icon: https://raw.githubusercontent.com/matifali/logos/main/pytorch-black.svg
    }
  }
  img3: TensorFlow {
    style: {
      stroke-dash: 10
      stroke-width: 1
    }
    tf: "" {
      shape: image
      icon: https://raw.githubusercontent.com/matifali/logos/main/tensorflow.svg
    }
  }
  img4: PyTorch + TensorFlow {
    style: {
      stroke-dash: 10
      stroke-width: 1
    }
    torch-tf: "" {
      shape: image
      icon: https://raw.githubusercontent.com/matifali/logos/main/tf-torch.svg
    }
  }
  img5: Conda {
    style: {
      stroke-dash: 10
      stroke-width: 1
    }
    conda: "" {
      shape: image
      icon: https://raw.githubusercontent.com/matifali/logos/main/conda.svg
    }
  }
  img6: Conda + PyTorch +\nTensorFlow {
    style: {
      stroke-dash: 10
      stroke-width: 1
    }
    torch-tf-conda: "" {
      shape: image
      icon: https://raw.githubusercontent.com/matifali/logos/main/tf-torch-conda.svg
    }
  }
}
